"""update profile fields to match Vue.js interface

Revision ID: 713263802e93
Revises: 8fa41465d6f6
Create Date: 2026-03-23 17:55:54.453887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '713263802e93'
down_revision: Union[str, None] = '8fa41465d6f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('stt', sa.Integer(), nullable=True, comment='Số thứ tự (nếu cần hiển thị theo thứ tự)'))
    op.add_column('profiles', sa.Column('ho_ten', sa.String(length=100), nullable=False, comment='Họ và tên'))
    op.add_column('profiles', sa.Column('ngay_sinh', sa.Date(), nullable=True, comment='Ngày sinh'))
    op.add_column('profiles', sa.Column('gioi_tinh', sa.Enum('NAM', 'NU', name='gender'), nullable=True, comment='Giới tính: Nam/Nữ'))
    op.add_column('profiles', sa.Column('cccd', sa.String(length=20), nullable=True, comment='Số CCCD/CMND'))
    op.add_column('profiles', sa.Column('ngay_tham_gia', sa.Date(), nullable=False, comment='Ngày tham gia hệ thống'))
    op.add_column('profiles', sa.Column('dia_chi', sa.String(length=255), nullable=True, comment='Địa chỉ'))
    op.create_unique_constraint(None, 'profiles', ['cccd'])
    op.drop_column('profiles', 'hometown')
    op.drop_column('profiles', 'full_name')
    op.drop_column('profiles', 'current_address')
    op.drop_column('profiles', 'date_of_birth')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('date_of_birth', sa.DATE(), nullable=True))
    op.add_column('profiles', sa.Column('current_address', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('profiles', sa.Column('full_name', mysql.VARCHAR(length=100), nullable=False))
    op.add_column('profiles', sa.Column('hometown', mysql.VARCHAR(length=100), nullable=True))
    op.drop_constraint(None, 'profiles', type_='unique')
    op.drop_column('profiles', 'dia_chi')
    op.drop_column('profiles', 'ngay_tham_gia')
    op.drop_column('profiles', 'cccd')
    op.drop_column('profiles', 'gioi_tinh')
    op.drop_column('profiles', 'ngay_sinh')
    op.drop_column('profiles', 'ho_ten')
    op.drop_column('profiles', 'stt')
    # ### end Alembic commands ###
