"""remove user relationship from profile, make it independent list

Revision ID: 8890a4924b6f
Revises: 713263802e93
Create Date: 2026-03-25 19:51:35.781390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8890a4924b6f'
down_revision: Union[str, None] = '713263802e93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('profiles_ibfk_1', 'profiles', type_='foreignkey')
    op.drop_column('profiles', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key('profiles_ibfk_1', 'profiles', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
