"""add paying unit table

Revision ID: b4b3c779c4bb
Revises: 8890a4924b6f
Create Date: 2026-04-01 20:39:31.007029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4b3c779c4bb'
down_revision: Union[str, None] = '8890a4924b6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paying_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ten_cong_ty', sa.String(length=200), nullable=False),
    sa.Column('ma_so_thue', sa.String(length=50), nullable=True),
    sa.Column('nguoi_dai_dien', sa.String(length=100), nullable=True),
    sa.Column('dia_chi', sa.String(length=300), nullable=True),
    sa.Column('loai_cong_ty', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ma_so_thue')
    )
    op.create_index(op.f('ix_paying_units_id'), 'paying_units', ['id'], unique=False)
    op.create_index(op.f('ix_paying_units_ten_cong_ty'), 'paying_units', ['ten_cong_ty'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_paying_units_ten_cong_ty'), table_name='paying_units')
    op.drop_index(op.f('ix_paying_units_id'), table_name='paying_units')
    op.drop_table('paying_units')
    # ### end Alembic commands ###
